// 计时器

export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';
export const RESET = 'RESET';

// LIST

export const LIST_FETCH_START = 'LIST_FETCH_START';
export const LIST_FETCH_SUCCESS = 'LIST_FETCH_SUCCESS';
export const LIST_FETCH_FAILURE = 'LIST_FETCH_FAILURE';
export const LIST_STATE_CHANGE = 'LIST_STATE_CHANGE';
export const LIST_FACTOR_CHANGE = 'LIST_FACTOR_CHANGE';

// LOGIN